stages:
  - build
  - test
  - push
  - deploy

build:
  stage: build
  script:
    - docker build -t contactcentre:$CI_BUILD_REF_NAME -f docker/Dockerfile .
  tags:
    - builder
    - london

test:
  stage: test
  script:
    - docker run -d --name contactcentre-$CI_BUILD_REF_NAME contactcentre:$CI_BUILD_REF_NAME
    - sleep 10 && docker logs contactcentre-$CI_BUILD_REF_NAME
    - if [ `docker inspect -f '{{ .State.Health.Status }}' contactcentre-$CI_BUILD_REF_NAME` != "healthy" ]; then exit 1; fi
    - docker rm -f contactcentre-$CI_BUILD_REF_NAME
  tags:
    - builder
    - london


push:
  stage: push
  script:
    - docker tag contactcentre:$CI_BUILD_REF_NAME 192.168.101.210:5000/contactcentre:$CI_BUILD_REF_NAME
    - docker push 192.168.101.210:5000/contactcentre:$CI_BUILD_REF_NAME
    - docker rmi -f $(docker images contactcentre:$CI_BUILD_REF_NAME --format '{{.ID}}')
  only:
    - master
    - staging
    - test
    - dev
    - ci
    - graphql-calls
  tags:
    - builder
    - london


deploy:
  stage: deploy
  script:
    - docker stack deploy --compose-file=docker/docker-compose.yml contactcentre-$CI_BUILD_REF_NAME
  only:
    - master
    - staging
    - test
    - dev
    - ci
    - graphql-calls
  tags:
    - deployer
    - london

