version: '3'

#
#
#

services:
  contactcentre:
    image: "192.168.101.210:5000/contactcentre:${CI_BUILD_REF_NAME}"
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - traefik.port=80
        - traefik.docker.network=traefik_front_net
        - traefik.frontend.rule=Host:${CI_BUILD_REF_NAME}.contactcentre.asergis.org
      restart_policy:
        condition: on-failure
    networks:
      - traefik_front_net
networks:
  traefik_front_net:
    external: true
